name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker image
        run: |
          docker build -t run-action .
      - name: save images to files
        run: |
          mkdir dist
          docker save run-action | gzip > dist/run-action-img.tar.gz
      - uses: actions/upload-artifact@v2
        with:
          name: run-action-image
          path: dist
    
  run:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: run-action-image
          path: dist
      - name: load image
        run: |
          gzip --decompress --stdout dist/run-action-img.tar.gz | docker load
      - name: run app
        run:
          docker run run-action python app.py
  integration:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: run-action-image
          path: dist
      - name: load image
        run: |
          gzip --decompress --stdout dist/run-action-img.tar.gz | docker load
      - name: integration-build
        run: |
          docker build -t run-integration integration -f integration/Dockerfile \
          --build-arg BASE_IMAGE=run-action --build-arg SOME_TOKEN=${{ secrets.SOME_TOKEN }}
      - name: run integration
        run:
          docker run run-integration python integration.py
          
          
